# Generated by Django 4.2.7 on 2025-06-24 19:33

import chamados.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=chamados.models.upload_anexo_path, verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('tamanho', models.PositiveIntegerField(verbose_name='Tamanho (bytes)')),
                ('tipo_arquivo', models.CharField(max_length=50, verbose_name='Tipo do Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
            ],
            options={
                'verbose_name': 'Anexo do Chamado',
                'verbose_name_plural': 'Anexos dos Chamados',
                'db_table': 'anexos_chamados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número do Chamado')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em Atendimento'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('equipamento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Equipamento')),
                ('localizacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização')),
                ('observacoes_tecnico', models.TextField(blank=True, null=True, verbose_name='Observações do Técnico')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atendido_em', models.DateTimeField(blank=True, null=True, verbose_name='Atendido em')),
                ('encerrado_em', models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'db_table': 'chamados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
                'db_table': 'tipos_servico',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('criado', 'Chamado Criado'), ('status_alterado', 'Status Alterado'), ('tecnico_atribuido', 'Técnico Atribuído'), ('tecnico_removido', 'Técnico Removido'), ('observacao_adicionada', 'Observação Adicionada'), ('anexo_adicionado', 'Anexo Adicionado'), ('anexo_removido', 'Anexo Removido')], max_length=30, verbose_name='Tipo da Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='chamados.chamado', verbose_name='Chamado')),
            ],
            options={
                'verbose_name': 'Histórico do Chamado',
                'verbose_name_plural': 'Histórico dos Chamados',
                'db_table': 'historico_chamados',
                'ordering': ['-criado_em'],
            },
        ),
    ]
